const UPDATE_LINE_DATA = 'UPDATE_LINE_DATA'
const UPDATE_BAR_DATA = 'UPDATE_BAR_DATA'
const UPDATE_SPIRAL_DATA = 'UPDATE_SPIRAL_DATA'

export default {
    UPDATE_BAR_DATA,
    UPDATE_LINE_DATA,
    UPDATE_SPIRAL_DATA
}